docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM CUSTOMERS where id > 1004;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Angela", "Aguilar", "rbean@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Ashley", "Weber", "wrightrobert@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Amanda", "Martinez", "brett43@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Chase", "Thompson", "rodneyclayton@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Sara", "Gill", "cathy45@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Stephen", "Pena", "jfranco@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Phillip", "Roberson", "andrew43@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Melanie", "Duffy", "kellybradford@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers WHERE id = 1010;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jared", "Wallace", "christine06@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Sarah", "Johnson", "phillip60@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Hannah", "Dickerson", "james20@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Brittney", "Jensen", "lynn42@example.net"),(NULL, "Rachel", "Miller", "ocoleman@example.net"),(NULL, "Keith", "Harris", "barbara34@example.org") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers where id between 1015 and 1018;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Raymond", "Cox", "ahensley@example.org"),(NULL, "Elizabeth", "Lucas", "victoriabauer@example.org"),(NULL, "Sherry", "Orr", "mwhite@example.net") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Karen", "Ross", "mitchellethan@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jennifer", "Kennedy", "ybrown@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Nichole", "Whitaker", "jonathanramirez@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Carl", "Smith", "kentkramer@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Derek", "Howell", "colleenpowell@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Carlos", "Patel", "pamela34@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Michelle", "Davis", "ringram@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jonathan", "Martinez", "charlotte54@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Thomas", "Zimmerman", "nicholsonkathy@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Nancy", "Thomas", "rogersbarbara@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Donna", "Grant", "ywilson@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "James", "Jensen", "olivia37@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Kristin", "Rodriguez", "cjohnson@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Katrina", "Robles", "callahanvictor@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Collin", "Carter", "eburgess@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Katherine", "Stevenson", "sallen@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jamie", "Wheeler", "erin59@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Alexander", "Moore", "tina64@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers where id = 1028;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Cindy", "Todd", "stephen09@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Michael", "Russell", "andersonerin@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Christopher", "Lowe", "travishill@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jared", "Green", "lijessica@example.org"),(NULL, "Glenn", "Collins", "jacobtorres@example.com"),(NULL, "Anna", "Schmidt", "alexanderrobinson@example.net") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers ORDER BY RAND() LIMIT 3;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jason", "Garrett", "monroealexander@example.org"),(NULL, "Mallory", "Smith", "christopher72@example.net"),(NULL, "Kaitlyn", "Freeman", "lori94@example.net") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Victoria", "Hickman", "stephen79@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Karen", "Murphy", "amahoney@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Heather", "Johns", "kmoore@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Benjamin", "Baker", "pmcintosh@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jonathon", "Burnett", "pkim@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Joshua", "Davis", "johnsjennifer@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Patrick", "Stone", "nancy97@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Amy", "Olson", "nixonjo@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Sara", "Frost", "vazquezstacey@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "John", "Martinez", "bcarson@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Shane", "Horton", "jwilliams@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Megan", "Stanton", "ralph23@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jennifer", "Wright", "cindyhodge@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Amanda", "Medina", "bakerlisa@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Luke", "Morrison", "paustin@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Sierra", "King", "whitedavid@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Danielle", "Curtis", "duartesamuel@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Katherine", "Stevens", "kjohns@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers ORDER BY RAND() LIMIT 1;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Danielle", "Garcia", "walkerchristina@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Robert", "Ingram", "osbornegary@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Daniel", "Nelson", "stephanie11@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Marc", "Hernandez", "scampbell@example.org"),(NULL, "Kristen", "Simmons", "prestondonna@example.com"),(NULL, "Daniel", "Warner", "kristyevans@example.net") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers where id between 1080 and 1092;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Danielle", "Vasquez", "elizabethreynolds@example.com"),(NULL, "Virginia", "Davis", "scottmedina@example.com"),(NULL, "John", "Haley", "monica28@example.org") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Vanessa", "Lopez", "wardjennifer@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Alexa", "Lewis", "collinsjustin@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Traci", "Johnson", "alice26@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Danny", "Whitney", "jorozco@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Michael", "Carlson", "leslie26@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Connie", "Lewis", "kmcclure@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Kristina", "Clark", "kennethwilliams@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Dillon", "Carlson", "kenneth70@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Amy", "Hayes", "hannah61@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Victoria", "Kidd", "loveelizabeth@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Michele", "Baker", "carolineclark@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Christopher", "Holt", "mark05@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "William", "Burns", "rowlandjim@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Briana", "Andrade", "frances80@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Sandra", "Reyes", "rjohnson@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Daniel", "Friedman", "perezscott@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Michael", "Thompson", "vanessabrown@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Sarah", "Patterson", "csolis@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers where id = 1110;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Tiffany", "Maldonado", "iwilliams@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Heather", "King", "nramirez@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Kelly", "Savage", "tracypatterson@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Thomas", "Jones", "avargas@example.net"),(NULL, "Ricky", "Marquez", "zacharynelson@example.org"),(NULL, "Stephanie", "Trujillo", "lopezkeith@example.org") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers ORDER BY RAND() LIMIT 3;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Angela", "Porter", "timothy80@example.com"),(NULL, "Jason", "Torres", "andrewstodd@example.com"),(NULL, "Brian", "Foster", "steven62@example.com") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Gregory", "Schmidt", "ashleykirk@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Kimberly", "Howard", "anita40@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jennifer", "Collins", "deborah78@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Michael", "Hartman", "guzmanlisa@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Morgan", "Leonard", "hbowman@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Denise", "Miller", "gregorysnyder@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Joshua", "Coffey", "whitney45@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Beth", "Wheeler", "charles23@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Benjamin", "Hernandez", "madisonyang@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Matthew", "Gilbert", "hubbardjeffrey@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jason", "Mcgee", "lucasherrera@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Stacey", "Griffin", "andrewbennett@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "James", "Baker", "iadams@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Darryl", "Adams", "albertadams@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Diane", "Hawkins", "jessica08@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Adriana", "Hall", "fernandezmichelle@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jennifer", "Harper", "bryantsean@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Emily", "Foster", "uramos@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers WHERE id > 1100;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Alice", "Downs", "richard39@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Micheal", "Griffin", "fhodge@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Rodney", "Murray", "lauramarquez@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Zachary", "Buck", "robinsonjennifer@example.net"),(NULL, "Evelyn", "Lewis", "mary33@example.org"),(NULL, "Jessica", "Guerrero", "johnflores@example.com") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers ORDER BY RAND() LIMIT 3;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jessica", "Foster", "vabbott@example.net"),(NULL, "Susan", "Joseph", "dwilliams@example.org"),(NULL, "Angelica", "Medina", "kwarren@example.net") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Christine", "Baker", "michellerhodes@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Thomas", "Daugherty", "mary46@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "John", "Murray", "campbellkenneth@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Sarah", "Combs", "fwinters@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Stephanie", "Watson", "vbarton@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "James", "Schultz", "hzimmerman@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Edgar", "Hatfield", "colton65@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Brandon", "Vincent", "glennhaley@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Nicholas", "Black", "elizabeth25@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Richard", "Garcia", "bbaker@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Stephanie", "Barron", "ulewis@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Thomas", "Hunter", "ynolan@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jennifer", "Hoover", "kallen@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Ashley", "Rhodes", "catherinesantos@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Julie", "Bates", "aaroncollier@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jonathan", "Johnson", "kristytaylor@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Thomas", "Hays", "ashleyortiz@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Julie", "Clark", "lstokes@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers ORDER BY RAND() LIMIT 1;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Thomas", "Colon", "sharonkeith@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Barbara", "Fisher", "ashley05@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Denise", "Anderson", "melissafranklin@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Anna", "Campbell", "nkennedy@example.org"),(NULL, "Jessica", "Jackson", "voconnell@example.net"),(NULL, "Henry", "Simon", "michaelbryant@example.net") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'DELETE FROM customers ORDER BY RAND() LIMIT 3;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Renee", "Thompson", "jeremygarcia@example.org"),(NULL, "Jacqueline", "Rivera", "phawkins@example.com"),(NULL, "Anita", "Neal", "djohnson@example.net") ;'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Jacqueline", "Miller", "robertbarton@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Andrea", "Gray", "phillipsjacob@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Elizabeth", "Cooper", "michelle38@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Angie", "Marquez", "robertcollins@example.org");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Roy", "Valenzuela", "bryan33@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Lynn", "Ruiz", "amoore@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Justin", "Vaughn", "heatherkelley@example.com");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Nicole", "Morris", "qevans@example.net");'
docker exec mysql mysql -umysqluser -pmysqlpw inventory -e 'INSERT INTO customers VALUES (NULL, "Madison", "Gomez", "ferrellamy@example.net");'
